DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `procLoadDS160`(IN `ProfileId` INT, IN `CountryId` INT, IN `VisaTypeId` INT)
BEGIN

 
 SELECT cp1.*,
       cp2.State_Province,
       cp2.PostalZone_ZIPCode,
       cp2.Country,
       cp2.Same_Mailing_Address,
       cp2.Mailing_Home_Address,
       cp2.Mailing_City,
       cp2.Mailing_State_Province,
       cp2.Mailing_PostalZone_ZIPCode,
       cp2.Mailing_Country,
       cp2.Home_Phone_Number,
       cp2.Work_Phone_Number,
       cp2.Work_Fax_Number,
       cp2.Mobile_Cell_Phone_Number,
       cp2.Email_Address,
       cp2.Passport_Number,
       cp2.Passport_Book_Number,
       cp2.Country_Authority_Issued_Passport,
       cp2.City_Issued_Passport,
       cp3.State_Province_Issued_Passport,
       cp3.Country_Issued_Passport,
       cp3.Issuance_Date_Passport,
       cp3.Expiration_Date_Passport,
       cp3.Passport_Stolen_Lost,
       ct1.Principal_Applicant,
	   ct1.Trip_Purpose_1,
	   ct1.Trip_Purpose_2,
	   ct1.Trip_Purpose_3,
	   ct1.Trip_Purpose_4,
	   ct1.Intended_Date_Of_Arrival,
	   ct1.Intended_Length_Of_Stay_US,
	   ct1.Address_of_US_Stay,
	   ct1.Person_Entity_Paying_US_Trip,
	   ct1.Telephone,
	   ct1.Email_Address Travel_Email_Address,
	   ct1.Relationship_To_You,
	   ct1.PayingPartyTripAddress_SameAsHomeMailingAddress,
	   ct1.PartyPayingAddress,
	   ct1.PartyPayingCity,
	   ct1.PartyPayingState_Province,
	   ct1.PostalZone_ZIPcode Travel_PostalZone_ZIPcode,
	   ct1.Country Travel_Country,
	   ct1.OtherPersonTravellingWithYou,
	   ct2.TravellingPartofGroup_Organizantion,
	   ct2.PersonTravellingWithYou_Name_1,
	   ct2.PersonTravellingWithYou_Name_2,
	   ct2.PersonTravellingWithYou_Name_3,
	   ct2.PersonTravellingWithYou_Name_4,
	   ct2.PersonTravellingWithYou_Name_5,
	   ct2.PersonTravellingWithYou_Relationship_1,
	   ct2.PersonTravellingWithYou_Relationship_2,
	   ct2.PersonTravellingWithYou_Relationship_3,
	   ct2.PersonTravellingWithYou_Relationship_4,
	   ct2.PersonTravellingWithYou_Relationship_5,
	   ct2.EverBeenToUS,
       ct2.EverBeenIssuedUSVisa,
	   ct2.EverBeenRefusedUSVisa_RefusedAdmissionToUS_WithdrawnApplication,
	   cu.ContactPersonNameInUS,
	   cu.OrganizationNameInUS,
	   cu.Relationship,
	   cu.ContactAddressUS,
	   cu.Phone_Number,
	   cu.Email_Address Contact_Email_Address,
	   cf1.FatherSurname,
	   cf1.FatherGivenName,
	   cf1.FatherDateofBirth,
	   cf1.IsYourFatherInUS,
	   cf1.MotherSurname,
	   cf1.MotherGivenName,
	   cf1.IsYourMotherInUS,
	   cf1.ImmediateRelativesInUS_ApartFatherMother,
	   cf1.Relative_Name_1,
	   cf1.Relationship_To_Relative_1,
	   cf1.Relative_Status_1,
	   cf1.Relative_Name_2,
	   cf1.Relationship_To_Relative_2,
	   cf1.Relative_Status_2,
	   cf1.Relative_Name_3,
	   cf1.Relationship_To_Relative_3,
	   cf1.Relative_Status_3,
	   cf2.Relative_Name_4,
	   cf2.Relationship_To_Relative_4,
	   cf2.Relative_Status_4,
	   cf2.Spouse_FullName,
	   cf2.Spouse_DateOfBirth,
	   cf2.Spouse_Nationality,
	   cf2.Spouse_CityOfBirth,
	   cf2.Spouse_CountryOfBirth,
	   cf2.Spouse_Address,
	   cw.Primary_Occupation,
	   cw.PresentEmployer_SchoolName,
	   cw.Address,
	   cw.City Work_City,
	   cw.State_Province,
	   cw.PostalZone_ZipCode Work_PostalZone_ZipCode,
	   cw.Country Work_Country,
	   cw.MonthSalary_LocalCurrency,
	   cw.BrifelyDescribeYourDuties,
	   cl.CurrentLocation,
	   cpa.AnyoneAssistInFillingApplication 
 FROM custpersonalinfo1 cp1
 LEFT JOIN custpersonalinfo2 cp2 ON cp1.CustAppInfoId = cp2.CustAppInfoId
 LEFT JOIN custpersonalinfo3 cp3 ON cp1.CustAppInfoId = cp3.CustAppInfoId
 LEFT JOIN custtravelinfo1 ct1 ON cp1.CustAppInfoId = ct1.CustAppInfoId
 LEFT JOIN custtravelinfo2 ct2 ON cp1.CustAppInfoId = ct2.CustAppInfoId
 LEFT JOIN custuscontactinfo cu ON cp1.CustAppInfoId = cu.CustAppInfoId
 LEFT JOIN custfamilyinfo cf1 ON cp1.CustAppInfoId = cf1.CustAppInfoId
 LEFT JOIN custfamilyinfo cf2 ON cp1.CustAppInfoId = cf2.CustAppInfoId
 LEFT JOIN custworkeducationtraininginfo cw ON cp1.CustAppInfoId = cw.CustAppInfoId
 LEFT JOIN custlocalinfo cl ON cp1.CustAppInfoId = cl.CustAppInfoId
 LEFT JOIN custpreparerappinfo cpa ON cp1.CustAppInfoId = cpa.CustAppInfoId
 WHERE cp1.CustAppInfoId = (SELECT CustAppInfoId FROM custappinfo where CustProfileInfoId = ProfileId and CountryListId = CountryId and CountryVisaTypeListId = VisaTypeId);



 END$$
DELIMITER ;