DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `procLoadH1B`(IN `UserName` VARCHAR(200))
BEGIN


            SELECT p1.FirstName,
                   p1.MiddleName,
                   p1.LastName,
                   p1.MaidenName,
                   p1.AliasFirstName,
                   p1.AliasLastName,
                   p1.OtherName1,
                   p1.OtherName2,
                   p1.OtherName3,
                   p1.EmailAddress,
                   p1.WorkPhone,
                   p1.HomePhone,
                   p1.MobilePhone,
                   p1.Gender,
                   p1.DateofBirth,
                   p1.CityofBirth,
                   p1.StateofBirth,
                   p1.CountryofBirth,
                   p2.Nationality,
                   p2.PermanentResident_Immigrant,
                   p2.RecentCitizenship_PR_Immigrant,
                   p2.PassportNumber,
                   p2.PassportIssueDate,
                   p2.PassportExpirationDate,
                   p2.PassportIssuedCity,
                   p2.PassportIssuedState,
                   p2.PassportIssuedCountry,
                   p2.BlankPagesInPassport,
                   ha.HaveUSHomeAddress,
                   ha.USHomeAddressDateFrom,
                   ha.USHomeAddressDateTo,
                   ha.StreetAddress USStreetAddress,
                   ha.Address2 USAddress2 ,
                   ha.City USCity,
                   ha.StateProvinceRegion USStateProvinceRegion,
                   ha.ZipCode USZipCode,
                   ha.Country USCountry,
                   ha.SameAsCurrentmaiingAddress,
                   ha.Address2_1,
                   ha.City_1,
                   ha.StateProvinceRegion_1,
                   ha.ZipCode_1,
                   ha.Country_1,
                   ha.PhoneNumberWithThisAddress,
                   ha.PlanOfChangingPlaceOfResidenceInNext4Months USPlanOfChangingPlaceOfResidenceInNext4Months,
                   ha.IfYesMovingDateAndNewAddress,
                   oa.OverseasPermanentAddressDateFrom,
                   oa.OverseasPermanentAddressDateTo,
                   oa.StreetAddress OSStreetAddress,
                   oa.Address2 OSAddress2,
                   oa.City OSCity,
                   oa.StateProvinceRegion OSStateProvinceRegion,
                   oa.ZipCode OSZipCode,
                   oa.Country OSCountry,
                   oa.PlanOfChangingPlaceOfResidenceInNext4Months OSPlanOfChangingPlaceOfResidenceInNext4Months,
                   e.InstitutionFullName,
                   e.InstitutionType,
                   e.InstitutionAccreditationStatus,
                   e.DateAttendedFrom,
                   e.DateAttendedTo,
                   e.MajorOrFieldOfStudy,
                   e.DegreeReceived,
                   e.Notes,
                   e1.EmploymentType,
                   e1.EmploymentDateFrom,
                   e1.EmploymentDateTo,
                   e1.StreetAddress EmpStreetAddress,
                   e1.Address2 EmpAddress2,
                   e1.City EmpCity,
                   e1.StateProvinceRegion EmpStateProvinceRegion,
                   e1.ZipCode EmpZipCode,
                   e1.Country EmpCountry,
                   e1.EmployerIsUniversityOrNonProfit,
                   e1.TypeOfBusiness,
                   e1.HoursPerWeek,
                   e1.IsPositionPartTime,
                   e1.JobTitle,
                   e1.CurrentAnnualBaseSalary,
                   e1.DetailJobDuties,
                   e1.TechnologiesUsed,
                   e2.SupervisorName,
                   e2.SupervisorPhoneNumber,
                   e2.SuperVisorJobTitle,
                   e2.AnyInterruptionsInEmploymentWithEmployer,
                   e2.WorkingOutsideTheUS,
                   e2.IfWorkingOutsideDoesItInvolveSupervision,
                   v1.EverEnteredUS,
                   v1.DateofLastEntryUS,
                   v1.I94Number,
                   v1.CurrentUSImmigrationStatus,
                   v1.LastEntryUSCity,
                   v1.LastEntryUSState,
                   v1.ExpirationStatusI94_I688,
                   v1.VisaNumber,
                   v1.VisaIssuanceCity,
                   v1.VisaIssuanceCountry,
                   v1.ViaIssuanceDate,
                   v1.VisaExpirationDate,
                   v1.EverFiledI140ImmigrationPetition,
                   v1.I140ApprovedDenied,
                   v1.I140PriorityDate,
                   v1.I140ReceiptCategoryPriorityDate,
                   v1.EverAppliedGreenCardOrPermanentResidencyByYou_Family,
                   v1.DatePlaceOutcomeOfGreenCardOrPermanentResidency,
                   v2.F1Status_CPTTraining,
                   v2.CPTWithGraduateDegree,
                   v2.StartedCPTAfterDegreeProgram,
                   v2.IfinF1_AppliedOTP,
                   v2.I765Approved_Pending,
                   v2.I765ReceiptNumber,
                   v2.IfI765Approved_NoOfDaysUnemployedAfterEAD,
                   v2.J1orJ2Visa,
                   v2.TwoYrHomeResidencyRequirement,
                   v2.J1orJ2SubmittedApplicationForWaiver,
                   v2.F1OrJ1SEVISNumber,
                   v2.EverBeenInUSInHOrLStatus,
                   v2.EverWorkedForNonProfitOrgResearchOrgUniversityInH1BStatus,
                   v2.FiledH1BDuringPreviousFiscalYear,
                   v2.AppliedH1BPursuantToApprovedPetitionAndEnterUS,
                   v2.StartedEmploymentInUS,
                   v2.NotStartedEmploymentSelectReason,
                   v2.HOrLPetitionDenied,
                   v2.IfYesEnterReason,
                   va.ResidingOutsideUS,
                   va.USConsulateLocationOutsideUS,
                   va.AppliedNonImmigrantUSVisa,
                   va.VisaCancelledDeniedRejected
                FROM personaldetail1 p1 
                LEFT JOIN personaldetail2 p2 ON p1.CustProfileInfoId = p2.CustProfileInfoId
                LEFT JOIN ushomeaddress ha ON p1.CustProfileInfoId = ha.CustProfileInfoId
                LEFT JOIN overseaspermanentaddress oa ON p1.CustProfileInfoId = oa.CustProfileInfoId
                LEFT JOIN education e ON p1.CustProfileInfoId = e.CustProfileInfoId
                LEFT JOIN employment1 e1 ON p1.CustProfileInfoId = e1.CustProfileInfoId
                LEFT JOIN employment2 e2 ON p1.CustProfileInfoId = e2.CustProfileInfoId
                LEFT JOIN internationtravel i ON p1.CustProfileInfoId = i.CustProfileInfoId
                LEFT JOIN visainformation1 v1 ON p1.CustProfileInfoId = v1.CustProfileInfoId
                LEFT JOIN visainformation2 v2 ON p1.CustProfileInfoId = v2.CustProfileInfoId
                LEFT JOIN visaapplication va ON p1.CustProfileInfoId = va.CustProfileInfoId
                LEFT JOIN custprofileinfo cp ON p1.CustProfileInfoId = cp.CustProfileInfoId
                WHERE cp.UserName = UserName;


END$$
DELIMITER ;