DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `procLoadH1BFromDS160`(IN `UserName` VARCHAR(200))
BEGIN


SELECT DS.FirstName,
       p1.MiddleName,
	   DS.LastName,
       DS.MaidenName,
       p1.AliasFirstName,
       p1.AliasLastName,
       DS.OtherName1,
       DS.OtherName2,
       DS.OtherName3,
       DS.EmailAddress,
       DS.WorkPhone,
       DS.HomePhone,
       DS.MobilePhone,
       DS.Gender,
       DS.DateofBirth,
       DS.CityofBirth,
       DS.StateofBirth,
       p1.CountryofBirth,
       DS.Nationality,
       p2.PermanentResident_Immigrant,
       p2.RecentCitizenship_PR_Immigrant,
       DS.PassportNumber,
       DS.PassportIssuedDate,
       DS.PassportExpirationDate,
       DS.PassportIssuedCity,
       DS.PassportIssuedState,
       DS.PassportIssuedCountry,
       p2.BlankPagesInPassport,
       ha.HaveUSHomeAddress,
       ha.USHomeAddressDateFrom,
       ha.USHomeAddressDateTo,
       ha.StreetAddress USStreetAddress,
       ha.Address2 USAddress2 ,
       ha.City USCity,
       ha.StateProvinceRegion USStateProvinceRegion,
       ha.ZipCode USZipCode,
       ha.Country USCountry,
       ha.SameAsCurrentmaiingAddress,
       ha.Address2_1,
       ha.City_1,
       ha.StateProvinceRegion_1,
       ha.ZipCode_1,
       ha.Country_1,
       ha.PhoneNumberWithThisAddress,
       ha.PlanOfChangingPlaceOfResidenceInNext4Months USPlanOfChangingPlaceOfResidenceInNext4Months,
       ha.IfYesMovingDateAndNewAddress,
       oa.OverseasPermanentAddressDateFrom,
       oa.OverseasPermanentAddressDateTo,
       oa.StreetAddress OSStreetAddress,
       oa.Address2 OSAddress2,
       oa.City OSCity,
       oa.StateProvinceRegion OSStateProvinceRegion,
       oa.ZipCode OSZipCode,
       oa.Country OSCountry,
       oa.PlanOfChangingPlaceOfResidenceInNext4Months OSPlanOfChangingPlaceOfResidenceInNext4Months,
       e.InstitutionFullName,
       e.InstitutionType,
       e.InstitutionAccreditationStatus,
       e.DateAttendedFrom,
       e.DateAttendedTo,
       e.MajorOrFieldOfStudy,
       e.DegreeReceived,
       e.Notes,
       e1.EmploymentType,
       e1.EmploymentDateFrom,
       e1.EmploymentDateTo,
       e1.StreetAddress EmpStreetAddress,
       e1.Address2 EmpAddress2,
       e1.City EmpCity,
       e1.StateProvinceRegion EmpStateProvinceRegion,
       e1.ZipCode EmpZipCode,
       e1.Country EmpCountry,
       e1.EmployerIsUniversityOrNonProfit,
       e1.TypeOfBusiness,
       e1.HoursPerWeek,
       e1.IsPositionPartTime,
       e1.JobTitle,
       e1.CurrentAnnualBaseSalary,
       e1.DetailJobDuties,
       e1.TechnologiesUsed,
       e2.SupervisorName,
       e2.SupervisorPhoneNumber,
       e2.SuperVisorJobTitle,
       e2.AnyInterruptionsInEmploymentWithEmployer,
       e2.WorkingOutsideTheUS,
       e2.IfWorkingOutsideDoesItInvolveSupervision,
       v1.EverEnteredUS,
       v1.DateofLastEntryUS,
       v1.I94Number,
       v1.CurrentUSImmigrationStatus,
       v1.LastEntryUSCity,
       v1.LastEntryUSState,
       v1.ExpirationStatusI94_I688,
       v1.VisaNumber,
       v1.VisaIssuanceCity,
       v1.VisaIssuanceCountry,
       v1.ViaIssuanceDate,
       v1.VisaExpirationDate,
       v1.EverFiledI140ImmigrationPetition,
       v1.I140ApprovedDenied,
       v1.I140PriorityDate,
       v1.I140ReceiptCategoryPriorityDate,
       v1.EverAppliedGreenCardOrPermanentResidencyByYou_Family,
       v1.DatePlaceOutcomeOfGreenCardOrPermanentResidency,
       v2.F1Status_CPTTraining,
       v2.CPTWithGraduateDegree,
       v2.StartedCPTAfterDegreeProgram,
       v2.IfinF1_AppliedOTP,
       v2.I765Approved_Pending,
       v2.I765ReceiptNumber,
       v2.IfI765Approved_NoOfDaysUnemployedAfterEAD,
       v2.J1orJ2Visa,
       v2.TwoYrHomeResidencyRequirement,
       v2.J1orJ2SubmittedApplicationForWaiver,
       v2.F1OrJ1SEVISNumber,
       v2.EverBeenInUSInHOrLStatus,
       v2.EverWorkedForNonProfitOrgResearchOrgUniversityInH1BStatus,
       v2.FiledH1BDuringPreviousFiscalYear,
       v2.AppliedH1BPursuantToApprovedPetitionAndEnterUS,
       v2.StartedEmploymentInUS,
       v2.NotStartedEmploymentSelectReason,
       v2.HOrLPetitionDenied,
       v2.IfYesEnterReason,
       va.ResidingOutsideUS,
       va.USConsulateLocationOutsideUS,
       va.AppliedNonImmigrantUSVisa,
       va.VisaCancelledDeniedRejected
        FROM (
                SELECT c1.First_Name FirstName,
                       c1.Last_Name LastName,
                       c1.Full_Name_In_Native_Language MaidenName,
                       c1.Other_Name_1 OtherName1,
                       c1.Other_Name_2 OtherName2,
                       c1.Other_Name_3 OtherName3,
                       c2.Email_Address EmailAddress,
                       c2.Work_Phone_Number WorkPhone,
                       c2.Home_Phone_Number HomePhone,
                       c2.Mobile_Cell_Phone_Number MobilePhone,
                       c1.Sex Gender,
                       c1.Date_Of_Birth DateofBirth,
                       c1.City_Of_Birth CityofBirth,
                       c1.State_Of_Birth StateofBirth,
                       c1.Nationality,
                       c2.Passport_Number PassportNumber,
                       c3.Issuance_Date_Passport PassportIssuedDate,
                       c3.Expiration_Date_Passport PassportExpirationDate,
                       c2.City_Issued_Passport PassportIssuedCity,
                       c3.State_Province_Issued_Passport PassportIssuedState,
                       c3.Country_Issued_Passport PassportIssuedCountry,
                       A.CustAppInfoId,
                       cp.UserName
                FROM custpersonalinfo1 c1 
                LEFT JOIN custpersonalinfo2 c2 ON c1.CustAppInfoId = c2.CustAppInfoId
                LEFT JOIN custpersonalinfo3 c3 ON c1.CustAppInfoId = c3.CustAppInfoId
                LEFT JOIN (SELECT cp.CustProfileInfoId,MAX(app.CustAppInfoId)CustAppInfoId FROM custappinfo app 
                           inner join custprofileinfo cp ON app.CustProfileInfoId = cp.CustProfileInfoId
                           WHERE cp.UserName = UserName
                           GROUP BY cp.CustProfileInfoId)A ON c1.CustAppInfoId = A.CustAppInfoId
                LEFT JOIN custprofileinfo cp ON cp.UserName = UserName
               WHERE c1.CustAppInfoId IN (SELECT CustAppInfoId FROM custappinfo WHERE CountryListId IN (SELECT CountryListId FROM countrylist WHERE CountryName = 'United States') AND CustProfileInfoId IN (SELECT CustProfileInfoId FROM custprofileinfo WHERE UserName = UserName)))DS
                LEFT JOIN personaldetail1 p1 ON DS.CustAppInfoId = p1.CustAppInfoId
                LEFT JOIN personaldetail2 p2 ON p1.CustAppInfoId = p2.CustAppInfoId
                LEFT JOIN ushomeaddress ha ON p1.CustAppInfoId = ha.CustAppInfoId
                LEFT JOIN overseaspermanentaddress oa ON p1.CustAppInfoId = oa.CustAppInfoId
                LEFT JOIN education e ON p1.CustAppInfoId = e.CustAppInfoId
                LEFT JOIN employment1 e1 ON p1.CustAppInfoId = e1.CustAppInfoId
                LEFT JOIN employment2 e2 ON p1.CustAppInfoId = e2.CustAppInfoId
                LEFT JOIN internationtravel i ON p1.CustAppInfoId = i.CustAppInfoId
                LEFT JOIN visainformation1 v1 ON p1.CustAppInfoId = v1.CustAppInfoId
                LEFT JOIN visainformation2 v2 ON p1.CustAppInfoId = v2.CustAppInfoId
                LEFT JOIN visaapplication va ON p1.CustAppInfoId = va.CustAppInfoId
                WHERE DS.UserName = UserName;

END$$
DELIMITER ;