CREATE TABLE `visainformation2` (
  `VisaInformationId` int(11) NOT NULL auto_increment primary key,
  `CustProfileInfoId` int(11) DEFAULT NULL,
   `F1Status_CPTTraining` varchar(50) DEFAULT NULL,
  `CPTWithGraduateDegree` varchar(50) DEFAULT NULL,
  `StartedCPTAfterDegreeProgram` varchar(50) DEFAULT NULL,
  `IfinF1_AppliedOTP` varchar(50) DEFAULT NULL,
  `I765Approved_Pending` varchar(50) DEFAULT NULL,
  `I765ReceiptNumber` varchar(100) DEFAULT NULL,
  `IfI765Approved_NoOfDaysUnemployedAfterEAD` int(11) DEFAULT NULL,
  `J1orJ2Visa` varchar(50) DEFAULT NULL,
  `TwoYrHomeResidencyRequirement` varchar(50) DEFAULT NULL,
  `J1orJ2SubmittedApplicationForWaiver` varchar(50) DEFAULT NULL,
  `F1OrJ1SEVISNumber` varchar(100) DEFAULT NULL,
  `EverBeenInUSInHOrLStatus` varchar(50) DEFAULT NULL,
  `EverWorkedForNonProfitOrgResearchOrgUniversityInH1BStatus` varchar(50) DEFAULT NULL,
  `FiledH1BDuringPreviousFiscalYear` varchar(50) DEFAULT NULL,
  `AppliedH1BPursuantToApprovedPetitionAndEnterUS` varchar(50) DEFAULT NULL,
  `StartedEmploymentInUS` varchar(50) DEFAULT NULL,
  `NotStartedEmploymentSelectReason` varchar(500) DEFAULT NULL,
  `HOrLPetitionDenied` varchar(50) DEFAULT NULL,
  `IfYesEnterReason` varchar(8000) DEFAULT NULL,
   Foreign key (CustProfileInfoId) references CustProfileInfo(CustProfileInfoId)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;